import Head from "next/head";
import Image from "next/image";
import React from "react";
import CssBaseline from "@mui/material/CssBaseline";
import Box from "@mui/material/Box";
import Container from "@mui/material/Container";
import FileUpload from "@/components/FileUploader/inedx";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<CssBaseline />
			<Head>
				<title>InfoSysCs | Home</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<React.Fragment>
				<Container maxWidth="lg">
					<Box sx={{ bgcolor: "#faf9f9" }}>
						<FileUpload />
					</Box>
				</Container>
			</React.Fragment>
		</>
	);
}
