import React from "react";
import Head from "next/head";
export default function HeadUI({ children, pageTitle }) {
	return (
		<Head>
			<title>InfoSysCs | {pageTitle}</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.svg" />
			{children}
		</Head>
	);
}
